### ISSUE TITLE
Sehr ineffizient

### ISSUE THREAD

**Issue by L3P3** [LFF5644/socketTCP#3]
Erstens wird die gesamte Datei jedes Mal in JSON umgewandelt und zurück. (WTF)

Zweitens wird für jeden Chunk die gesamte Datei durchgegangen und jedes Byte einzeln angefügt, obwohl es extra für sowas `buffer.slice(start, end)` gibt!

**Comment by LFF5644** [comment]
aua das wuste ich nicht

**Comment by LFF5644** [comment]
https://github.com/LFF5644/socketTCP/commit/fe4b42984c36abe4e7782d5d50a513dc5b26ddeb
